### ISSUE TITLE
preparedstatement values not escaped

### ISSUE THREAD

**Issue by p1tz** [orientechnologies/orientdb-jdbc#30]
It goes like this, main use case for using prepared statements is to get rid of the escaping hell (orient-jdbc 2.1)

    sth.setString("a \"b\" c", (String) val);

or sth.setObject ...

results in 

com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #36: Invalid keyword ...". Use UPDATE <class>|cluster:<cluster>> [SET|ADD|PUT|REMOVE|INCREMENT|CONTENT {<JSON>}|MERGE {<JSON>}] [[,] <field-name> = <expression>|<sub-command>]* [LOCK <NONE|RECORD>] [UPSERT] [RETURN <COUNT|BEFORE|AFTER>] [WHERE <conditions>]
Command: UPDATE bla SET bla = "a "b" c" WHERE id = "bla"
--------------------------------------------^
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.throwSyntaxErrorException(OCommandExecutorSQLAbstract.java:98)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.parse(OCommandExecutorSQLUpdate.java:182)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.parse(OCommandExecutorSQLUpdate.java:60)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:76)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:42)
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.command(ODistributedStorage.java:230)

**Comment by luigidellaquila** [comment]
Hi @p1tz 

probably it was related to https://github.com/orientechnologies/orientdb/issues/4885
It was fixed in branch 2.1.x and 2.1.1 hotfix will be released in a few hours.
Could you please try it again and let me know?

Thanks

Luigi

**Comment by p1tz** [comment]
verified, fixed, thank you :+1:
